hotels_travel_categories = {"Airports",
                            "Bed & Breakfast",
                            "Campgrounds",
                            "Car Rental",
                            "Guest Houses",
                            "Hostels",
                            "Hotels",
                            "Rest Stops",
                            "RV Parks",
                            "RV Rental",
                            "Resorts",
                            "Ski Resorts",
                            "Limos",
                            "Taxis",
                            "Travel Services",
                            "Luggage Storage",
                            "Passport & Visa Services",
                            "Travel Agents",
                            "Visitor Centers",
                            "Vacation Rental Agents",
                            "Vacation Rentals"}
